version: '3.9'

services:
  app1:
    build:
      context: .
    container_name: app1
    environment:
      - CONTAINER_NAME=app1

  app2:
    build:
      context: .
    container_name: app2
    environment:
      - CONTAINER_NAME=app2

  app3:
    build:
      context: .
    container_name: app3
    environment:
      - CONTAINER_NAME=app3

  app4:
    build:
      context: .
    container_name: app4
    environment:
      - CONTAINER_NAME=app4


  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2